config/routes.rb
Rails.application.routes.draw do
  get 'index', to: 'static_pages#index'
  get 'tutorial', to: 'static_pages#tutorial'
  get 'tables', to: 'static_pages#tables'
  root 'static_pages#index'

  get 'options/answer'
  get 'options/dices'
  get 'options/travel'
  get 'options/encounters'
  get 'options/missions'
  get 'options/dungeons'
  get 'options/terrain'
  get 'options/city'
  get 'options/npcs'
  get 'options/element'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :option_view

  def answer; end

  def dices; end

  def travel; end

  def encounters; end

  def missions; end

  def dungeons; end

  def terrain; end

  def city; end

  def npcs; end

  def element; end

  private

  def option_view
    @resp = params[:param1]
    respond_to do |format|
      format.js
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def tutorial
  end

  def tables
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/shared/_footer.html.erb
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">by <a href="https://github.com/mateusflorez" target="blank" style="text-decoration: none; color: #000000">Mateus Paz</a></div>
            <div class="text-muted">
                Feel free to give me a <a href="https://github.com/mateusflorez/ttrpg-generator" target="blank" style="text-decoration: none; color: #000000">star</a>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/shared/_header.html.erb
<header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <%= link_to root_path, class: "d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none" do %>
            <%= image_tag("d20", size: "40") %>
        <% end %>
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to "Gerador", index_path, class: "nav-link px-2 link-dark" %></li>
            <li><%= link_to "Tabelas", tables_path, class: "nav-link px-2 link-dark" %></li>
            <li><%= link_to "Tutoriais", tutorial_path, class: "nav-link px-2 link-dark" %></li>
        </ul>
        </div>
    </div>
</header>

app/views/options/answer.js.erb
$(function(){

    //Set dice
    const dices = [20];

    //Randomize
    <%= render :partial => 'options/shared/randomizer' %>

    //Dificulty modifier
    var res;
    switch (<%= @resp %>) {
        case 1:
            res = rndInt[1]-6;
            break;
        case 2:
            res = rndInt[1]-4;
            break;
        case 3:
            res = rndInt[1]-2;
            break;
        case 4:
            res = rndInt[1];
            break;
        case 5:
            res = rndInt[1]+2;
            break;
        case 6:
            res = rndInt[1]+4;
            break;
        case 7:
            res = rndInt[1]+6;
            break;
        case 8:
            res = rndInt[1];
            break;
    }

    //results
    if (<%= @resp %> === 8){
        if (res <= 10){
            res = "Não"
        } else{
            res = "Sim"
        }
    } else if (res <= 6){
        res = "Não"
    } else if (res > 6 && res < 13){
        res = "Talvez"
    } else {
        res = "Sim"
    }

    //Set history
    <%= render :partial => 'options/shared/set_history' %>

    //Save
    <%= render :partial => 'options/shared/save' %>

    //Print
    <%= render :partial => 'options/shared/print' %>

});

app/views/options/city.js.erb
$(function(){

    //Set dice
    const dices = [20];

    //Randomize
    <%= render :partial => 'options/shared/randomizer' %>

    <%= render :partial => 'options/city/shop/merchantquality' %>
    <%= render :partial => 'options/city/shop/itemquality' %>

    //Option selector
    var res = "";
    switch (<%= @resp %>) {
        //Shops
        case 1:
            <%= render :partial => 'options/city/shops' %>
            break;
        //Merchant
        case 2:
            <%= render :partial => 'options/city/merchant' %>
            break;
        //Rumors
        case 3:
            <%= render :partial => 'options/city/rumor' %>
            break;
    }

    //Set history
    <%= render :partial => 'options/shared/set_history' %>

    //Save
    <%= render :partial => 'options/shared/save' %>

    //Print
    <%= render :partial => 'options/shared/print' %>

});

app/views/options/city/shop/_itemquality.js.erb
function itemQualityRandomizer(merchantquality) {
    rand = minMaxRandomizer(1, 20);
    var quality = " §Raridade de item máxima:";
    switch (merchantquality) {
        case 1:
            if (rand < 15) {
                quality += " Comum.";
            } else if (rand > 14 && rand < 19) {
                quality += " Incomum.";
            } else {
                quality += " Raro.";
            }
            return quality;
            break;
        case 2:
            if (rand < 13) {
                quality += " Comum.";
            } else if (rand > 12 && rand < 18) {
                quality += " Incomum.";
            } else {
                quality += " Raro.";
            }
            return quality;
            break;
        case 3:
            if (rand < 11) {
                quality += " Comum.";
            } else if (rand > 10 && rand < 16) {
                quality += " Incomum.";
            } else if (rand > 15 && rand < 19) {
                quality += " Raro.";
            } else {
                quality += " Lendário.";
            }
            return quality;
            break;
        case 4:
            if (rand < 9) {
                quality += " Comum.";
            } else if (rand > 8 && rand < 14) {
                quality += " Incomum.";
            } else if (rand > 13 && rand < 18) {
                quality += " Raro.";
            } else {
                quality += " Lendário.";
            }
            return quality;
            break;
        case 5:
            if (rand < 7) {
                quality += " Comum.";
            } else if (rand > 6 && rand < 13) {
                quality += " Incomum.";
            } else if (rand > 12 && rand < 17) {
                quality += " Raro.";
            } else {
                quality += " Lendário.";
            }
            return quality;
            break;
    }
}

app/views/options/city/shop/_merchantquality.js.erb
function merchantQualityRandomizer() {
    rand = minMaxRandomizer(1, 20);
    var quality = "";
    if (rand < 6) {
        quality += " §Qualidade: Terrível. "+itemQualityRandomizer(1);
    } else if (rand > 5 && rand < 10) {
        quality += " §Qualidade: Pobre. "+itemQualityRandomizer(2);
    } else if (rand > 9 && rand < 14) {
        quality += " §Qualidade: Médio. "+itemQualityRandomizer(3);
    } else if (rand > 13 && rand < 18) {
        quality += " §Qualidade: Bom. "+itemQualityRandomizer(4);
    } else {
        quality += " §Qualidade: Excelente. "+itemQualityRandomizer(5);
    }
    return quality;
}

app/views/options/dices.js.erb
$(function(){

    //Set dice
    const dices = [<%= @resp %>];

    //Randomize
    <%= render :partial => 'options/shared/randomizer' %>

    //Var set
    var res = rndInt[1];

    //Set history
    <%= render :partial => 'options/shared/set_history' %>

    //Save
    <%= render :partial => 'options/shared/save' %>

    //Print
    <%= render :partial => 'options/shared/print' %>

});

app/views/options/dungeons.js.erb
$(function(){

    //Set dice
    const dices = [20, 10, 100, 100, 20, 20, 100, 20];

    //Randomize
    <%= render :partial => 'options/shared/randomizer' %>

    //Area randomizers
    <%= render :partial => 'options/dungeons/area/passage' %>
    <%= render :partial => 'options/dungeons/area/door' %>
    <%= render :partial => 'options/dungeons/area/stair' %>
    <%= render :partial => 'options/dungeons/area/room' %>
    <%= render :partial => 'options/dungeons/area/architecture' %>
    <%= render :partial => 'options/dungeons/area/secretdoor' %>
    <%= render :partial => 'options/dungeons/area/trap' %>
    <%= render :partial => 'options/dungeons/area/clue' %>

    //Option selector
    var res;
    switch (<%= @resp %>) {
        //Mission
        case 1:
            <%= render :partial => 'options/dungeons/dungeon' %>
            break;
        //Source
        case 2:
            <%= render :partial => 'options/dungeons/area' %>
            break;
    }

    //Set history
    <%= render :partial => 'options/shared/set_history' %>

    //Save
    <%= render :partial => 'options/shared/save' %>

    //Print
    <%= render :partial => 'options/shared/print' %>

});

app/views/options/dungeons/_area.js.erb
if (rndInt[2] < 3) {
    res = passageRandomizer();
} else if (rndInt[2] > 2 && rndInt[2] < 5) {
    res = roomRandomizer();
} else if (rndInt[2] > 4 && rndInt[2] < 7) {
    res = doorRandomizer();
} else if (rndInt[2] > 6 && rndInt[2] < 9) {
    res = stairRandomizer();
} else {
    temp1 = minMaxRandomizer(1, 100);
    if (temp1 < 51) {
       res = passageRandomizer();
    }
    else {
        res = roomRandomizer();
    }
}

app/views/options/dungeons/_dungeon.js.erb
//variables
var size = ""
var type = ""
var rooms = ""

//function
if (rndInt[1] < 4) {
    size = "Minúsculo(a)";
    rooms = minMaxRandomizer(1, 4)+2;
} else if (rndInt[1] > 3 && rndInt[1] < 9) {
    size = "Pequeno(a)";
    rooms = minMaxRandomizer(1, 6)+4;
} else if (rndInt[1] > 8 && rndInt[1] < 17) {
    size = "Médio(a)";
    rooms = minMaxRandomizer(4, 16)+6;
} else if (rndInt[1] > 16 && rndInt[1] < 19) {
    size = "Grande";
    rooms = minMaxRandomizer(5, 30)+12;
} else if (rndInt[1] === 19) {
    size = "Enorme";
    rooms = minMaxRandomizer(10, 60)+24;
} else {
    size = "Ilimitado(a)";
}

if (rndInt[2] === 1) {
    type = "Covil";
} else if (rndInt[2] === 2) {
    type = "Tumba / Cripta";
} else if (rndInt[2] === 3) {
    type = "Fortaleza abandonada";
} else if (rndInt[2] === 4) {
    type = "Templo ou santuário";
} else if (rndInt[2] === 5) {
    type = "Cavernas naturais";
} else if (rndInt[2] === 6) {
    type = "Labirinto";
} else if (rndInt[2] === 7) {
    type = "Mina";
} else if (rndInt[2] === 8) {
    type = "Portão Planar";
} else if (rndInt[2] === 9) {
    type = "Sede de guilda/culto";
} else {
    type = "Armadilha mortal";
}

if (rooms != ""){
    res = type+" "+size+". "+rooms+" quartos";
} else {
    res = type+" "+size+".";
}

app/views/options/dungeons/_secretdoor.js.erb
function sdRandomizer() {
    rand = minMaxRandomizer(1, 6);
    var sd = "";
    if (rand < 3) {
        rndInt[7] += 40;
        sd = "A porta secreta se abre para uma sala. ";
    } else if (rand < 2 && rand < 5) {
        rndInt[3] += 40;
        sd = "A porta secreta abre para a passagem.";
    }  else {
        temp1 = minMaxRandomizer(1, 100);
        var temp = "";
        if (temp1 < 51) {
            rndInt[3] += 50;
            temp += "passagem. "+passageRandomizer();
        } else {
            rndInt[7] += 50
            temp += "sala. "+roomRandomizer();
        }
        sd = "Porta secreta presa. "+trapRandomizer()+". Do outro lado há uma "+temp;
    }
    return sd;
}

app/views/options/element.js.erb
$(function(){

    //Set dice
    const dices = [20];

    //Randomize
    <%= render :partial => 'options/shared/randomizer' %>

    //Option selector
    var res = "";
    switch (<%= @resp %>) {
        //Urban event
        case 1:
            <%= render :partial => 'options/element/urbanevent' %>
            break;
        //Wild event
        case 2:
            <%= render :partial => 'options/element/wildevent' %>
            break;
        //Creatures
        case 3:
            <%= render :partial => 'options/element/creature' %>
            break;
        //Situations
        case 4:
            <%= render :partial => 'options/element/situations' %>
            break;
        //Elements
        case 5:
            <%= render :partial => 'options/element/element' %>
            break;
    }

    //Set history
    <%= render :partial => 'options/shared/set_history' %>

    //Save
    <%= render :partial => 'options/shared/save' %>

    //Print
    <%= render :partial => 'options/shared/print' %>

});

app/views/options/encounters.js.erb
$(function(){

    //Set dice
    const dices = [100, 100, 100, 100, 100];

    //Randomize
    <%= render :partial => 'options/shared/randomizer' %>

    //Option selector
    var res;
    switch (<%= @resp %>) {
        //Wild
        case 1:
            <%= render :partial => 'options/encounters/wild' %>
            break;
        //Urban
        case 2:
            <%= render :partial => 'options/encounters/urban' %>
            break;
        //Dungeon
        case 3:
            <%= render :partial => 'options/encounters/dungeon' %>
            break;
    }

    //Set history
    <%= render :partial => 'options/shared/set_history' %>

    //Save
    <%= render :partial => 'options/shared/save' %>

    //Print
    <%= render :partial => 'options/shared/print' %>

});

app/views/options/missions.js.erb
$(function(){

    //Set dice
    const dices = [100];

    //Randomize
    <%= render :partial => 'options/shared/randomizer' %>

    //Option selector
    var res;
    switch (<%= @resp %>) {
        //Mission
        case 1:
            <%= render :partial => 'options/missions/mission' %>
            break;
        //Source
        case 2:
            <%= render :partial => 'options/missions/source' %>
            break;
    }

    //Set history
    <%= render :partial => 'options/shared/set_history' %>

    //Save
    <%= render :partial => 'options/shared/save' %>

    //Print
    <%= render :partial => 'options/shared/print' %>

});

app/views/options/npcs.js.erb
$(function(){

    //Set dice
    const dices = [20];

    //Randomize
    <%= render :partial => 'options/shared/randomizer' %>

    <%= render :partial => 'options/npcs/shared/alignment' %>
    <%= render :partial => 'options/npcs/shared/gender' %>
    <%= render :partial => 'options/npcs/shared/race' %>
    <%= render :partial => 'options/npcs/shared/profession' %>
    <%= render :partial => 'options/npcs/shared/class' %>
    <%= render :partial => 'options/npcs/shared/disposition' %>
    <%= render :partial => 'options/npcs/shared/economicstatus' %>

    //Option selector
    var res = "";
    switch (<%= @resp %>) {
        //Random
        case 1:
            <%= render :partial => 'options/npcs/random' %>
            break;
        //Worker
        case 2:
            <%= render :partial => 'options/npcs/worker' %>
            break;
        //Adventurer
        case 3:
            <%= render :partial => 'options/npcs/adventurer' %>
            break;
    }

    //Set history
    <%= render :partial => 'options/shared/set_history' %>

    //Save
    <%= render :partial => 'options/shared/save' %>

    //Print
    <%= render :partial => 'options/shared/print' %>

});

app/views/options/npcs/_adventurer.js.erb
//Race
res += raceRandomizer();

//Gender
res += genderRandomizer();

//Alignment
res += alignmentRandomizer();

//Profession
res += adventurerClassRandomizer();

//Disposition
res += dispositionRandomizer();

//Economic status
res += economicStatusRandomizer();

app/views/options/npcs/_random.js.erb
//Race
res += raceRandomizer();

//Gender
res += genderRandomizer();

//Alignment
res += alignmentRandomizer();

//Profession
rand = minMaxRandomizer(1, 100);
if (rand < 26) {
    res += "Plebeu (desempregado).";
} else if (rand > 25 && rand < 91) {
    res += professionRandomizer();
} else {
    res += adventurerClassRandomizer();
}

//Disposition
res += dispositionRandomizer();

//Economic status
res += economicStatusRandomizer();

app/views/options/npcs/_worker.js.erb
//Race
res += raceRandomizer();

//Gender
res += genderRandomizer();

//Alignment
res += alignmentRandomizer();

//Profession
res += professionRandomizer();

//Disposition
res += dispositionRandomizer();

//Economic status
res += economicStatusRandomizer();

app/views/options/npcs/shared/_alignment.js.erb
function alignmentRandomizer() {
    var alignment = "";
    rand = minMaxRandomizer(1, 100);
    if (rand < 16) {
        alignment += "Leal bom.§";
    } else if (rand > 15 && rand < 21) {
        alignment += "Neutro bom.§";
    } else if (rand > 20 && rand < 26) {
        alignment += "Caótico bom.§";
    } else if (rand > 25 && rand < 31) {
        alignment += "Leal neutro.§";
    } else if (rand > 30 && rand < 51) {
        alignment += "Neutro.§";
    } else if (rand > 50 && rand < 56) {
        alignment += "Caótico neutro.§";
    } else if (rand > 55 && rand < 71) {
        alignment += "Leal mal.§";
    } else if (rand > 70 && rand < 91) {
        alignment += "Neutro mal.§";
    } else {
        alignment += "Caótico mal.§";
    }
    return alignment;
}

app/views/options/npcs/shared/_gender.js.erb
function genderRandomizer() {
    var gender = "";
    rand = minMaxRandomizer(1, 100);
    if (rand < 51) {
        gender += "macho.§";
    } else {
        gender += "fêmea.§";
    }
    return gender;
}

app/views/static_pages/tutorial.html.erb
<div class="p-5 bg-light rounded m-3">
<h1 class="display-4 fw-normal text-center">Tutoriais</h1>

<br>
<br>
<div class="accordion accordion-flush" id="accordionFlushExample">
  <%= render "static_pages/shared/accordion_start", number: "One" %>
    Dados
  <%= render "static_pages/shared/accordion_mid", number: "One" %>
    Caso precise rodar um dado, selecione o botão com a quantidade de lados desejada!
  <%= render "static_pages/shared/accordion_end" %>
  <%= render "static_pages/shared/accordion_start", number: "Two" %>
    Mecânica de perguntas
  <%= render "static_pages/shared/accordion_mid", number: "Two" %>
    Faça uma pergunta, essa pergunta precisa ser formulada de forma que possa ser respondida com uma das três palavras a seguir: <b>sim</b>, <b>não</b>, <b>talvez</b>.
    <br>
    Dadas todas as circunstâncias, qual é a probabilidade da resposta ser sim? <b>Impossível?</b> Uma <b>certeza?</b>
    <br>
    Com a pergunta feita, clique no gerador de respostas e tenha a resposta para sua pergunta.
    <br>
    Caso a resposta precise ser respondida com <b>sim</b> ou <b>não</b> e tenha caído <b>talvez</b> em sua rolagem, rode a opção <b>50/50</b> para obter esta resposta.
    <br>
    Exemplo: "Eu sou perturbado por algo durante o acampamento?", caso tenha preparado um bom acampamento a chance é menor, então role a probabilidade <b>Difícil</b>
  <%= render "static_pages/shared/accordion_end" %>
  <%= render "static_pages/shared/accordion_start", number: "Three" %>
    Viagem
  <%= render "static_pages/shared/accordion_mid", number: "Three" %>
    Aqui seguem um conjunto de regras e informações para que possa viajar no seu mundo de fantasia. (Recomendo deixar uma aba no seu navegador com a página de tabelas aberta).
    <br><br>
    <b>Forma de viagem</b><br>
    Primeiro, defina a forma que seu personagem irá viajar (A pé, cavalo, etc), para mais informações confira os modos de viagem em <%= link_to "Tabelas", tables_path, style: "text-decoration: underline; color: black" %>.
    <br><br>
    <b>Clima</b><br>
    Após isso, role o <i>clima</i> que estará fazendo durante a viagem.
    <br><br>
    <b>Encontros</b><br>
    Após isso role 4 vezes para <i>encontros</i> caso esteja viajando durante o dia e 2 vezes caso esteja viajando a noite a cada 12 horas de viagem (Aumente ou diminua a quantidade dependendo da densidade populacional!).
    <br><br>
    <b>Assentamentos</b><br>
    Role 1d4, role <i>assentamentos</i> vezes o resultado do dado para ter a chance de encontrar assentamentos durante sua viagem. Caso encontre um assentamento use testes de <i>Perguntas/Respostas</i> para obter mais informações sobre ele!
    <br><br>
    <b>Acampamento</b><br>
    Confira a <%= link_to "tabela", tables_path, style: "text-decoration: underline; color: black" %> de acampamento para saber a Classe de Dificuldade para encontrar acampamento no terreno em que está.
    <br><br>
    <b>Perturbações</b><br>
    Faça um teste de <i>Perguntas/Respostas</i> para saber se seu personagem é perturbado durante o sono. Ajuste a probabilidade de acordo com a qualidade do acampamento.
  <%= render "static_pages/shared/accordion_end" %>
  <%= render "static_pages/shared/accordion_start", number: "Four" %>
    Missão
  <%= render "static_pages/shared/accordion_mid", number: "Four" %>
    Depois de gerar uma missão e sua fonte, faça as seguintes perguntas O QUÊ, POR QUÊ, QUANDO, ONDE, COMO e QUEM.
    <br>
    Para responder estas perguntas use o <i>gerador de respostas</i> e sua imaginação para encontrar as respostas.
    <br><br>
    Exemplo: "Item perdido"
    <br><br>
    <b>O QUÊ</b> era o item? Era mágico? um livro de feitiços?
    <br>
    <b>POR QUÊ</b> foi perdido? Foi roubado? Por quem?
    <br>
    <b>QUANDO</b> foi perdido? Recentemente, ou séculos atrás?
    <br>
    <b>ONDE</b> se diz que está? alguém tem ideia da localização dele?
    <br>
    <b>COMO</b> pode ser recuperado? Se a ocalização não for conhecida, existe alguma forma de descobrir a localização?
    <br>
    <b>QUEM</b> o alertou sobre a ausência do item? É alguém que você conhece? Alguém cuja confiabilidade é incerta?
    <br><br>
    Após a conclusão bem-sucedida de uma missão que resulte na melhoria do bem-estar dos moradores de uma vila, vila ou cidade, ou outro assentamento, os personagens podem descobrir que seu renome aumenta.
  <%= render "static_pages/shared/accordion_end" %>
  <%= render "static_pages/shared/accordion_start", number: "Five" %>
    Masmorras
  <%= render "static_pages/shared/accordion_mid", number: "Five" %>
    Quando se deparar com uma masmorra, primeiramente role para <i>Masmorra</i>, para definir o tamanho e o tipo.<br>
    Depois disso, role <i>Área</i> para cada sala que seu personagem passar dentro da masmorra, você pode rolar até a quantidade total de salas ou até encontrar seu objetivo.<br>
    Caso algum quarto pelo qual você passe não fizer sentido ou tenha chegado ao final da masmorra sem encontrar seu objetivo, sinta-se livre para usar sua imaginação, como colocar seu objetivo na sala final da masmorra, rolar <i>Área</i> novamente, ou até mesmo rolar <i>Situações</i>, talvez algo tenha acontecido com seu objetivo!
  <%= render "static_pages/shared/accordion_end" %>
  <%= render "static_pages/shared/accordion_start", number: "Six" %>
    Terreno
  <%= render "static_pages/shared/accordion_mid", number: "Six" %>
    Durante suas viajens entre aventuras ou de um assentamento a outro você pode encontrar diversas coisas, assim como na realidade o mundo é vivo e de um ponto a outro você encontrará muitos microcosmos e ambientes menores.<br>
    Primeiro, determine que tipo de terreno geral você está percorrendo. Assim como explicado na parte de viajens role os encontros para cada 12 horas de viajem.<br>
    Após isso role o terreno pelo qual você está percorrendo a cada 5 milhas de viagem. Talvez você encontre pistas ou até mesmo novos objetivos!
    <br><br>
    <b>Área ativa</b><br>
    Você pode estar viajando para esta área para chegar a um local onde há rumores de que a atividade está ocorrendo. Por exemplo, feras selvagens estão atacando o gado e há rumores de que estão à espreita aqui.<br>
    Quando você chegar a essas Áreas Ativas, role <i>Áreas Ativas</i> para determinar o que você encontra.
  <%= render "static_pages/shared/accordion_end" %>
  <%= render "static_pages/shared/accordion_start", number: "Seven" %>
    Cidade
  <%= render "static_pages/shared/accordion_mid", number: "Seven" %>
    Quando chegar a um assentamento novo seja ele conhecido ou não talvez você esteja tentando encontrar um tipo especializado de negócio/instituição.<br>
    Para saber os negócios disponíveis neste assentamento, role <i>Comércios</i>. Desta forma você pode ver os comércios disponíveis neste assentamento, sua qualidade e a raridade máxima dos itens que você pode encontrar a venda.
    <br><br>
    <b>Rumores</b><br>
    Quando estiver na taverna local ou passeando pela cidade você pode acabar ouvindo alguns rumores, role 1d4 vezes ou quantas vezes achar necessário.<br>
    Ao escutar estes rumores, seus personagens como aventureiros proativos podem buscar saber mais para solucionar o problema e encontrar novas aventuras!
  <%= render "static_pages/shared/accordion_end" %>
  <%= render "static_pages/shared/accordion_start", number: "Eight" %>
    NPC's
  <%= render "static_pages/shared/accordion_mid", number: "Eight" %>
    Em suas viagens, aventuras ou nos assentamentos por onde você passar, você encontrará todo tipo de gente. Para isso você pode rolar para um NPC aleatório, ou um trabalhador ou aventureiro em específico dependendo do que você precisar enquanto estiver se aventurando.
  <%= render "static_pages/shared/accordion_end" %>
  <%= render "static_pages/shared/accordion_start", number: "Nine" %>
    Elementos da história
  <%= render "static_pages/shared/accordion_mid", number: "Nine" %>
    Os elementos da história podem ser rolados para uma infinidade de utilidades. Seja para resolver uma pergunta, para encontrar novas missões, interagir com o mundo, ou gerar um evento ou missão. Seja criativo!<br>
    Role <i>Elementos</i> para gerar um encontro, supondo que resulte em duas jogadas em <i>PESSOAS</i> e uma jogada em <i>EVENTOS</i> e <i>SITUAÇÕES</i>.<br>
    Em pessoas tenha caído um humano mago e em situações as palavras <b>Aproveite</b>, <b>espie</b>, <b>exploda</b>.<br>
    Ao ligar estes elementos podemos imaginar um encontro em que um mago, carregando uma bolsa de poções pela estrada, tem a bolsa rasgada por algumas crianças travessas aproveitando da situação.<br>
    Poções se espalham pela estrada e explodem, para o deleite das crianças, e todo tipo de caos mágico acontece!<br>
    Sinta-se livre para rolar novamente como for necessário, adaptar as situações ao tema da sua aventura e seja criativo!
  <%= render "static_pages/shared/accordion_end" %>
</div>
</div>